# Generated by Django 4.0.6 on 2022-07-28 07:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
