# Generated by Django 4.0.6 on 2022-07-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_help', '0003_useraddress_creator_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'UserAddress'},
        ),
    ]
