# Generated by Django 4.0.6 on 2022-07-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_help', '0004_alter_useraddress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'User Address'},
        ),
    ]
