# Generated by Django 4.0.6 on 2022-07-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_help', '0005_alter_customuser_options_alter_useraddress_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='creator_type',
            new_name='created_by',
        ),
    ]
